### ISSUE TITLE
Missing processing for us_nation_5m?

### ISSUE THREAD

**Issue by TomAugspurger** [makepath/census-parquet#2]
I might be missing it, but I don't see how the `cb_2020_us_nation_5m.zip` file is downloaded / processed. Just need to add it to `download_boundaries.sh`?

**Comment by nodell111** [comment]
Thanks for catching this @TomAugspurger  `download_boundaries.sh` has been updated to include `cb_2020_us_nation_5m.zip` and a new release has been made with this change, didn't realize initially it wasn't in the bulk file - I just double-checked all the other files as well.
